version: 2.1
orbs:
  # The python orb contains a set of prepackaged circleci configuration you can use repeatedly in your configurations files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.4.1
workflows:
  EsportsLOLPrediction:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - Prepare environment to Data Ingestion and Extraction
      - Data Ingestion and Extraction:
            requires:
                - Prepare environment to Data Ingestion and Extraction

jobs:
  Prepare environment to Data Ingestion and Extraction:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "dd:72:bb:51:fd:66:b8:15:14:cd:27:21:36:a3:4b:a5"
      - run:
          name: Run Prepare.py
          command: python Prepare.py
      - run:
          name: Push changes to GitHub
          command: |
            git config user.email "blasko.gergo.hungmail.com"
            git config user.name "CircleCI Job"
            git checkout main
            git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
            git push origin main
  Data Ingestion and Extraction:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Run IngestThenExtractData.py
          command: python IngestThenExtractData.py
          
